version: "2"

volumes:
    indexer-modules:

services:
    indexer:
        image: node:12-stretch
        hostname: indexer
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
        mem_limit: 512M
        volumes:
            - $PWD:/srv/indexer:delegated
            - $PWD/../ocfl-repository:/srv/repository:delegated
            - indexer-modules:/srv/indexer/node_modules:delegated
        working_dir: /srv/indexer
        command: ["/bin/bash"]
