version: "2"

volumes:
    indexer-modules:
    search:

services:
    search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        hostname: search
        environment:
            - node.name=search
            - discovery.seed_hosts=search
            - bootstrap.memory_lock=true
            - http.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - search:/usr/share/elasticsearch/data:delegated
            - $PWD/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - $PWD/elastic/roles.yml:/usr/share/elasticsearch/config/roles.yml
            - $PWD/elastic/users:/usr/share/elasticsearch/config/users
            - $PWD/elastic/users_roles:/usr/share/elasticsearch/config/users_roles
        ports:
            - 9200:9200
